name = "sg1.veteran-tailor.cloud"
main = "src/index.ts"
compatibility_date = "2023-11-21"
routes = [
    "sg1.veteran-tailor.cloud/*",
    "*.sg1.veteran-tailor.cloud/*",
]

[vars]
API_HOST = "sg1.veteran-tailor.cloud"
